Repository Apres-Ski/Apres-Ski-FE, pull requests merged in 2023-02, with the labels that each got.

#6 Matt/feature/restaurants list
  index.html
  src/App.tsx
  src/app/store/interfaces.ts
  src/app/store/store.ts
  src/features/users/index.tsx
  src/features/users/restaurants/restaurantsSlice.tsx
  src/main.tsx
  src/utilities/APICalls.ts
  src/utilities/constants.ts
  src/utilities/utilities.ts
Labels: bug

#8 Tricia/fix/finish restaurants slice
  src/App.tsx
  src/app/store/interfaces.ts
  src/app/store/store.ts
  src/features/restaurants/restaurantsSlice.tsx
  src/features/users/index.tsx
  src/features/users/restaurants/restaurantsSlice.tsx
  src/utilities/APICalls.ts
  src/utilities/utilities.ts
Labels: FE, setup, Redux

#32 Add prettierrc file and settings
  .prettierrc.json
  package-lock.json
  package.json
  src/components/Landing.tsx
  src/features/users/Nav.tsx
Labels: FE, setup

#33 Matt/feature/routes setup
  package-lock.json
  package.json
  src/App.tsx
  src/app/App.tsx
  src/app/store.ts
  src/components/DemoUsers.tsx
  src/components/Error.tsx
  src/components/Landing.tsx
  src/components/Map.tsx
  src/components/NavComp.tsx
  src/components/RestaurantList/RestaurantList.tsx
  src/components/Sorry.tsx
  src/features/common/Map.tsx
  src/features/restaurants/Dashboard.tsx
  src/features/restaurants/RestaurantCard.tsx
  src/features/restaurants/RestaurantList.tsx
  src/features/restaurants/restaurantsSlice.tsx
  src/features/users/DemoUsers.tsx
  src/features/users/Nav.tsx
  src/features/users/UsersList.tsx
  src/main.tsx
  src/utilities/interfaces.ts
  src/utilities/utilities.ts
Labels: FE, functionality

#34 Add Filter component with initial onClicks
  src/features/common/Map.tsx
  src/features/restaurants/Dashboard.tsx
  src/features/restaurants/Filter.tsx
Labels: enhancement, FE, setup

#42 Ryan/feature/cypress install
  cypress.config.ts
  cypress/e2e/landing.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: FE, testing

#47 Tricia/fix/ts errors
  cypress/e2e/landing.cy.ts
  index.html
  package-lock.json
  package.json
  src/utilities/constants.ts
  tsconfig.json
Labels: FE, fix

#49 Ryan/fix/update data structure
  src/features/restaurants/RestaurantCard.tsx
  src/features/restaurants/restaurantsSlice.tsx
  src/utilities/interfaces.ts
  src/utilities/utilities.ts
Labels: FE, functionality

#62 Tricia/feature/add users fetch
  src/features/restaurants/Dashboard.tsx
  src/features/users/DemoUsers.tsx
  src/features/users/UsersList.tsx
  src/features/users/usersSlice.tsx
  src/utilities/APICalls.ts
  src/utilities/constants.ts
  src/utilities/interfaces.ts
  src/utilities/utilities.ts
Labels: enhancement, FE, functionality

#59 Add restaurant markers with placeholder icon
  src/assets/lift.png
  src/assets/lift2.png
  src/assets/restaurant.png
  src/features/common/Map.tsx
  src/index.css
  src/utilities/interfaces.ts
Labels: FE, functionality, styling

#61 Add functionality to logout button
  src/features/users/Nav.tsx
  src/features/users/usersSlice.tsx
Labels: FE, Redux, functionality

#66 Tricia/feature/nav format
  package-lock.json
  package.json
  src/App.css
  src/app/App.tsx
  src/features/restaurants/Dashboard.tsx
  src/features/users/Nav.tsx
  src/features/users/UsersList.tsx
  src/main.tsx
  src/utilities/constants.ts
Labels: FE, styling, refactor

#69 Ryan/feature/error modal v2
  src/app/App.tsx
  src/components/Error.tsx
  src/features/restaurants/Dashboard.tsx
  src/features/users/DemoUsers.tsx
Labels: FE, styling

#71 Ryan/feature/lift state
  src/app/App.tsx
  src/app/store.ts
  src/features/lifts/liftsSlice.ts
  src/features/restaurants/Dashboard.tsx
  src/utilities/APICalls.ts
  src/utilities/constants.ts
  src/utilities/interfaces.ts
  src/utilities/utilities.ts
Labels: FE, Redux, functionality

#75 Matt/feature/detailsv2 setup
  src/components/Landing.tsx
  src/features/common/Map.tsx
  src/features/filters/Filter.tsx
  src/features/restaurants/DetailModal.tsx
  src/features/restaurants/HappyHours.tsx
  src/features/restaurants/RestaurantCard.tsx
  src/features/restaurants/RestaurantList.tsx
  src/features/restaurants/restaurantsSlice.ts
  src/features/users/DemoUsers.tsx
  src/features/users/Nav.tsx
  src/features/users/UsersList.tsx
  src/main.tsx
  src/utilities/interfaces.ts
  src/utilities/utilities.ts
Labels: FE, functionality

#70 Filtering Logic
  src/app/store.ts
  src/features/filters/Filter.tsx
  src/features/filters/filtersSlice.ts
  src/features/restaurants/Dashboard.tsx
  src/features/restaurants/Filter.tsx
  src/features/restaurants/RestaurantCard.tsx
  src/features/restaurants/RestaurantList.tsx
  src/features/restaurants/restaurantsSlice.ts
  src/features/users/usersSlice.ts
  src/utilities/interfaces.ts
  src/utilities/utilities.ts
Labels: FE, Redux, functionality, styling, Mgmt Review

#79 Fe/temp main
  src/app/App.tsx
  src/app/store.ts
  src/components/Landing.tsx
  src/features/common/Map.tsx
  src/features/filters/Filter.tsx
  src/features/lifts/liftsSlice.ts
  src/features/restaurants/Dashboard.tsx
  src/features/restaurants/DetailModal.tsx
  src/features/restaurants/HappyHours.tsx
  src/features/restaurants/RestaurantCard.tsx
  src/features/restaurants/RestaurantList.tsx
  src/features/restaurants/restaurantsSlice.ts
  src/features/users/DemoUsers.tsx
  src/features/users/Nav.tsx
  src/features/users/UsersList.tsx
  src/index.css
  src/main.tsx
  src/utilities/APICalls.ts
  src/utilities/constants.ts
  src/utilities/interfaces.ts
  src/utilities/utilities.ts
Labels: FE, Redux, functionality, styling

#80 Ryan/feature/map layout styling
  src/App.css
  src/app/App.tsx
  src/features/common/Map.tsx
  src/features/restaurants/Dashboard.tsx
  src/features/restaurants/RestaurantCard.tsx
  src/features/restaurants/RestaurantList.tsx
  src/features/restaurants/restaurantsSlice.ts
  src/index.css
  src/utilities/constants.ts
  src/utilities/interfaces.ts
Labels: FE, styling

#104 Tricia/fix/phone size
  src/App.css
  src/features/users/DemoUsers.tsx
  src/features/users/Nav.tsx
Labels: styling
